apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-golang-app
  labels:
    app: sample-golang-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-golang-app
  template:
    metadata:
      labels:
        app: sample-golang-app
    spec:
      containers:
      - name: sample-golang
        image: akashgreninja/baisi:latest
        ports:
        - containerPort: 4000
