apiVersion: v1
kind: Service
metadata:
  name: sample-golang-application
spec:
  type: NodePort
  selector:
    app: sample-golang-app
  ports:
    - port: 80

      targetPort: 4000
  
      nodePort: 30007